apiVersion: v1
kind: ConfigMap
metadata:
  name: simplechat-config
  namespace: simplechat
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://simplechat-postgres/simplechat
  SPRING_RABBITMQ_HOST: simplechat-rabbitmq
  SPRING_RABBITMQ_USERNAME: user
  SPRING_RABBITMQ_PASSWORD: admin
  SPRING_REDIS_HOST: simplechat-redis
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://simplechat-eureka:8081/eureka