spring:
  application:
    name: eureka
server:
  port: 8081
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://localhost:8081/eureka
  instance:
    prefer-ip-address: true