apiVersion: apps/v1
kind: Deployment
metadata:
  name: simplechat-app
  namespace: simplechat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simplechat-app
  template:
    metadata:
      labels:
        app: simplechat-app
    spec:
      containers:
      - name: simplechat-app
        image: localhost:5000/simplechat-app:latest
        env:
          - name: SERVER_PORT
            value: "8082"
        envFrom:
          - configMapRef:
              name: simplechat-config