apiVersion: apps/v1
kind: Deployment
metadata:
  name: simplechat-redis
  namespace: simplechat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simplechat-redis
  template:
    metadata:
      labels:
        app: simplechat-redis
    spec:
      containers:
      - name: simplechat-redis
        image: redis:latest
        ports:
        - containerPort: 6379