apiVersion: v1
kind: Service
metadata:
  name: simplechat-app
  namespace: simplechat
spec:
  selector:
    app: simplechat-app
  ports:
    - port: 8082
      targetPort: 8082
  type: ClusterIP