apiVersion: v1
kind: Service
metadata:
  name: simplechat-chats
  namespace: simplechat
spec:
  selector:
    app: simplechat-chats
  ports:
    - port: 8083
      targetPort: 8083
  type: ClusterIP