apiVersion: v1
kind: Service
metadata:
  name: simplechat-gateway
  namespace: simplechat
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000
  selector:
    app: simplechat-gateway