apiVersion: v1
kind: Service
metadata:
  name: simplechat-postgres
  namespace: simplechat
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: simplechat-postgres