apiVersion: v1
kind: Service
metadata:
  name: simplechat-redis
  namespace: simplechat
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: simplechat-redis